# PyTorch로 시작하는 딥러닝 입문
## 1. 파이토치 기초
### 파이토치 패키지의 기본 구성
1. torch
- 메인 네임스페이스로 텐서, 수학 함수 등이 포함 돼 있으며 Numpy와 유사한 구조를 가짐

2. torch.autograd
- 자동 미분을 위한 함수가 포함 돼 있으며 on/off로 제어 가능

3. torch.nn
- 신경망을 구축하기 위한 다양한 데이터 구조나 레이어가 정의 돼 있음

4. torch.optim
- 확률적 경사 하강법(SGD)을 중심으로 한 파라미터 최적화 알고리즘이 구현돼 있음

5. torch.utils.data
- SGD의 반복 연산을 실행할때 사용하는 미니 배치용 유틸리티 함수

6. torch.onnx
- ONNX(Open Neural Network Exchange)의 포멧으로 모델을 익스포트(export) 할 때 사용하며 다른 프레임워크 간 모델을 공유할 때 사용하는 포멧

### 텐서 조작하기(Tensor Manipulation)
#### 넘파이로 텐서 만들기(벡터와 행렬 만들기)

In [ ]:
import numpy as np

In [ ]:
# 1D with Numpy
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [ ]:
print('Rank of t:', t.ndim)
print('Shape of t:', t.shape)

Rank of t: 1
Shape of t: (7,)


In [ ]:
# Numpy 기초 이해하기
print('t[0] t[1] t[-1] =', t[0], t[1], t[-1])

t[0] t[1] t[-1] = 0.0 1.0 6.0


In [ ]:
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1])

t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]


In [ ]:
print('t[:2] t[3:]     = ', t[:2], t[3:])

t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


In [ ]:
# 2D with Numpy
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [ ]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank  of t:  2
Shape of t:  (4, 3)


#### 파이토치 텐서 선언하기

In [ ]:
import torch

In [ ]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [ ]:
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


In [ ]:
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])  

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [ ]:
# 2D with PyTorch
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
print(t.dim())
print(t.size())

2
torch.Size([4, 3])


In [ ]:
print(t[:, :-1])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [ ]:
# 브로드캐스팅(Broadcasting)
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)
print(m1 * m2)

tensor([[5., 5.]])
tensor([[6., 6.]])


In [ ]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3]])
print(m1 + m2)
print(m1 * m2)

tensor([[4., 5.]])
tensor([[3., 6.]])


In [ ]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)
print(m1 * m2)

tensor([[4., 5.],
        [5., 6.]])
tensor([[3., 6.],
        [4., 8.]])


In [ ]:
# 자주 사용되는 기능들
# 행렬 곱셈과 곱셈의 차이
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print(m1.matmul(m2)) # 행렬 곱셈

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [ ]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print(m1 * m2)
print(m1.mul(m2)) # 곱셈

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [ ]:
# 평균(Mean)
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.mean()) # 4개의 원소의 평균 값

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)


In [ ]:
print(t.shape)
print(t.mean(dim=0)) # dim = 0 는 행렬에서 행을 뜻하며 dim = 0는 행을 제외하고 열의 평균을 내라는 의미
print(t.mean(dim=1)) # dim = 1 는 행렬에서 열을 뜻하며 dim = 1는 열을 제외하고 행의 평균을 내라는 의미

torch.Size([2, 2])
tensor([2., 3.])
tensor([1.5000, 3.5000])


In [ ]:
# 덧셈(Sum)
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])


In [ ]:
# 최대(Max)와 아그맥스(ArgMax)
# Max는 최대값 리턴, ArgMax는 최대값을 가진 인덱스 리턴
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.max())
print(t.max(dim=0))
print(t.max(dim=1))

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [ ]:
# 뷰(View)
# Numpy의 reshape 함수와 같은 역할
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft)
print(ft.shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])


In [ ]:
# 3차원 텐서에서 2차원 텐서로 변경
print(ft.view([-1, 3])) # 텐서를 (?, 3)의 크기로 변환하라
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [ ]:
# 3차원 텐서의 크기 변경
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [ ]:
# 스퀴즈(Squeeze)
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [ ]:
# 언스퀴즈(Unsqueeze)
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [ ]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape) # 첫번째 차원에 1 추가

print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape) # 두번째 차원에 1추가

print(ft.view(-1, 1))
print(ft.view(-1, 1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
# 타입 캐스팅(Type Casting)
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)
print(lt.type())

tensor([1, 2, 3, 4])
torch.LongTensor


In [ ]:
print(lt.float().type())

torch.FloatTensor


In [ ]:
bt = torch.ByteTensor([False, True, False, True])
print(bt)
print(bt.type())

tensor([0, 1, 0, 1], dtype=torch.uint8)
torch.ByteTensor


In [ ]:
# 연결하기(concatenate)
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
print(torch.cat([x, y], dim = 0)) # 행 결합
print(torch.cat([x, y], dim = 1)) # 열 결합

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [ ]:
# 스택킹(Stacking)
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])
print(torch.stack([x, y, z])) # 순서대로 1행, 2행, 3행
print(torch.stack([x, y, z]).shape)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
torch.Size([3, 2])


In [ ]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0).shape)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
torch.Size([3, 2])


In [ ]:
print(torch.stack([x, y, z], dim=1))
print(torch.stack([x, y, z], dim=1).shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


In [ ]:
# ones_like와 zeros_like
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# n-place Operation (덮어쓰기 연산)
x = torch.FloatTensor([[1, 2], [3, 4]])
print(x.mul(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(x.mul_(2.)) # mul에 '_' 를 추가하여 x에 연산한 값을 저장, x = x.mul(2.)
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


### 파이썬 클래스(class)
#### 함수(function)과 클래스(Class)의 차이

In [ ]:
# 함수(function)로 덧셈기 구현하기
result = 0

def add(num):
    global result
    result += num
    return result

In [ ]:
print(add(3))
print(add(4))

3
7


In [ ]:
# 함수(function)로 두 개의 덧셈기 구현하기
result1 = 0
result2 = 0

def add1(num):
    global result1
    result1 += num
    return result1

def add2(num):
    global result2
    result2 += num
    return result2

print(add1(3))
print(add1(4))
print(add2(3))
print(add2(7))

3
7
3
10


In [ ]:
# 클래스(class)로 덧셈기 구현하기
class Calculator:
    def __init__(self):
        self.result = 0

    def add(self, num):
        self.result += num
        return self.result

In [ ]:
cal1 = Calculator() # 객체 생성
cal2 = Calculator()

print(cal1.add(3))
print(cal1.add(4))
print(cal2.add(3))
print(cal2.add(7))

3
7
3
10
