# PyTorch로 시작하는 딥러닝 입문
## 2. 선형 회귀
### 선형 회귀

#### 파이토치로 선형 회귀 구현하기

In [ ]:
# 기본 세팅
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
torch.manual_seed(1)

In [ ]:
# 변수 선언
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [ ]:
x_train, x_train.shape

(tensor([[1.],
         [2.],
         [3.]]), torch.Size([3, 1]))

In [ ]:
y_train, y_train.shape

(tensor([[2.],
         [4.],
         [6.]]), torch.Size([3, 1]))

In [ ]:
# 가중치와 편향의 초기화
W = torch.zeros(1, requires_grad=True)
print(W)

tensor([0.], requires_grad=True)


In [ ]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


In [ ]:
# 가설 세우기
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [ ]:
# 비용 함수 선언하기
cost = torch.mean((hypothesis - y_train) ** 2) 
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [ ]:
# 경사 하강법 구현하기
optimizer = optim.SGD([W, b], lr=0.01)

In [ ]:
optimizer.zero_grad() # gradient 0으로 초기화
cost.backward() # 비용 함수 미분하여 gradient 계산
optimizer.step() # W와 b 업데이트

In [ ]:
# 전체 코드
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 2000 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/2000 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/2000 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/2000 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/2000 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/2000 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/2000 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/2000 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/2000 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/2000 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/2000 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/2000 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/2000 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/2000 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/2000 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/2000 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/2000 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/2000 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/2000 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/2000 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/2000 W: 1.997, b: 0.008 Cost: 0.000008

#### optimizer.zero_grad()가 필요한 이유


In [ ]:
import torch
w = torch.tensor(2.0, requires_grad=True)

nb_epochs = 20
for epoch in range(nb_epochs+1):
    z = 2*w
    z.backward()
    print('수식을 w로 미분한 값 : {}'.format(w.grad)) # 이전 값을 누적해 계산

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0


### 자동 미분


#### 자동 미분(Autograd) 실습하기

In [ ]:
import torch
w = torch.tensor(2.0, requires_grad=True)

In [ ]:
y = w**2
z = 2*y + 5

In [ ]:
z.backward()

In [ ]:
# z를 w로 미분했을 때 : 2 * 2 * w = 2 * 2 * 2 = 8
print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 8.0


#### 다중 선형 회귀

In [ ]:
# 파이토치로 구현하기
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
torch.manual_seed(1)

In [ ]:
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [ ]:
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [ ]:
optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b

    cost = torch.mean((hypothesis - y_train) ** 2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
        ))

Epoch    0/1000 w1: 0.718 w2: 0.612 w3: 0.680 b: 0.009 Cost: 1.078964
Epoch  100/1000 w1: 0.722 w2: 0.608 w3: 0.680 b: 0.009 Cost: 1.038180
Epoch  200/1000 w1: 0.727 w2: 0.603 w3: 0.681 b: 0.010 Cost: 0.999513
Epoch  300/1000 w1: 0.731 w2: 0.599 w3: 0.681 b: 0.010 Cost: 0.962859
Epoch  400/1000 w1: 0.735 w2: 0.595 w3: 0.681 b: 0.010 Cost: 0.928092
Epoch  500/1000 w1: 0.739 w2: 0.590 w3: 0.681 b: 0.010 Cost: 0.895123
Epoch  600/1000 w1: 0.743 w2: 0.586 w3: 0.682 b: 0.010 Cost: 0.863870
Epoch  700/1000 w1: 0.746 w2: 0.582 w3: 0.682 b: 0.010 Cost: 0.834221
Epoch  800/1000 w1: 0.750 w2: 0.579 w3: 0.682 b: 0.010 Cost: 0.806112
Epoch  900/1000 w1: 0.754 w2: 0.575 w3: 0.682 b: 0.010 Cost: 0.779432
Epoch 1000/1000 w1: 0.757 w2: 0.571 w3: 0.682 b: 0.011 Cost: 0.754143


#### 행렬 연산을 고려하여 파이토치로 구현하기

In [ ]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  90], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [ ]:
x_train.shape, y_train.shape

(torch.Size([5, 3]), torch.Size([5, 1]))

In [ ]:
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [ ]:
hypothesis = x_train.matmul(W) + b

In [ ]:
# 전체 코드
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  90], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

    hypothesis = x_train.matmul(W) + b

    cost = torch.mean((hypothesis - y_train) ** 2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([67.2578, 80.8397, 79.6523, 86.7394, 61.6605]) Cost: 9298.520508
Epoch    2/20 hypothesis: tensor([104.9128, 126.0990, 124.2466, 135.3015,  96.1821]) Cost: 2915.712402
Epoch    3/20 hypothesis: tensor([125.9942, 151.4381, 149.2133, 162.4896, 115.5097]) Cost: 915.040527
Epoch    4/20 hypothesis: tensor([137.7967, 165.6247, 163.1911, 177.7112, 126.3307]) Cost: 287.936096
Epoch    5/20 hypothesis: tensor([144.4044, 173.5674, 171.0168, 186.2332, 132.3891]) Cost: 91.371063
Epoch    6/20 hypothesis: tensor([148.1035, 178.0143, 175.3980, 191.0042, 135.7812]) Cost: 29.758249
Epoch    7/20 hypothesis: tensor([150.1744, 180.5042, 177.8509, 193.6753, 137.6805]) Cost: 10.445267
Epoch    8/20 hypothesis: tensor([151.3336, 181.8983, 179.2240, 195.1707, 138.7440]) Cost: 4.391237
Epoch    9/20 hypothesis: tensor([151.9824, 182.6789, 179.9928, 196.0079, 139.3396]) Cost: 2.493121
Epoch   10/20 hypo

#### nn.Module로 구현하는 선형 회귀

In [44]:
# 단순 선형 회귀 구현하기
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

In [45]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [46]:
model = nn.Linear(1, 1) # input_dim, output_dim

In [48]:
print(list(model.parameters())) # W와 b 값

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [49]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [50]:
nb_epochs = 2000

for epoch in range(nb_epochs + 1):
    
    prediction = model(x_train) # H(x)

    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost : {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/2000 Cost : 13.103541
Epoch  100/2000 Cost : 0.002791
Epoch  200/2000 Cost : 0.001724
Epoch  300/2000 Cost : 0.001066
Epoch  400/2000 Cost : 0.000658
Epoch  500/2000 Cost : 0.000407
Epoch  600/2000 Cost : 0.000251
Epoch  700/2000 Cost : 0.000155
Epoch  800/2000 Cost : 0.000096
Epoch  900/2000 Cost : 0.000059
Epoch 1000/2000 Cost : 0.000037
Epoch 1100/2000 Cost : 0.000023
Epoch 1200/2000 Cost : 0.000014
Epoch 1300/2000 Cost : 0.000009
Epoch 1400/2000 Cost : 0.000005
Epoch 1500/2000 Cost : 0.000003
Epoch 1600/2000 Cost : 0.000002
Epoch 1700/2000 Cost : 0.000001
Epoch 1800/2000 Cost : 0.000001
Epoch 1900/2000 Cost : 0.000000
Epoch 2000/2000 Cost : 0.000000


In [51]:
new_var = torch.FloatTensor([[4.0]])
pred_y = model(new_var)
print('훈련 후 입력이 4일 때의 예측값 :', pred_y)

훈련 후 입력이 4일 때의 예측값 : tensor([[7.9989]], grad_fn=<AddmmBackward>)


In [52]:
print(list(model.parameters())) # W의 값은 2에 가깝고 b는 0에 가까움

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


In [53]:
# 다중 선형 회귀 구현하기
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

In [54]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [56]:
model = nn.Linear(3, 1)

In [57]:
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [58]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [59]:
nb_epochs = 2000

for epoch in range(nb_epochs + 1):
    
    prediction = model(x_train)

    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 31667.597656
Epoch  100/2000 Cost: 0.225993
Epoch  200/2000 Cost: 0.223911
Epoch  300/2000 Cost: 0.221941
Epoch  400/2000 Cost: 0.220059
Epoch  500/2000 Cost: 0.218271
Epoch  600/2000 Cost: 0.216575
Epoch  700/2000 Cost: 0.214950
Epoch  800/2000 Cost: 0.213413
Epoch  900/2000 Cost: 0.211952
Epoch 1000/2000 Cost: 0.210560
Epoch 1100/2000 Cost: 0.209232
Epoch 1200/2000 Cost: 0.207967
Epoch 1300/2000 Cost: 0.206761
Epoch 1400/2000 Cost: 0.205619
Epoch 1500/2000 Cost: 0.204522
Epoch 1600/2000 Cost: 0.203484
Epoch 1700/2000 Cost: 0.202485
Epoch 1800/2000 Cost: 0.201542
Epoch 1900/2000 Cost: 0.200635
Epoch 2000/2000 Cost: 0.199769


In [60]:
new_var =  torch.FloatTensor([[73, 80, 75]]) 

pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.2305]], grad_fn=<AddmmBackward>)


In [61]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]


#### 클래스로 파이토치 모델 구현하기

In [62]:
# 단순 선형 회귀 클래스로 구현하기
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

In [63]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [67]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)

    def forward(self, x):
        return self.linear(x)

In [69]:
model = LinearRegressionModel()

In [70]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) 

In [71]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    prediction = model(x_train)

    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 13.510777
Epoch  100/2000 Cost: 0.040541
Epoch  200/2000 Cost: 0.025052
Epoch  300/2000 Cost: 0.015480
Epoch  400/2000 Cost: 0.009566
Epoch  500/2000 Cost: 0.005911
Epoch  600/2000 Cost: 0.003653
Epoch  700/2000 Cost: 0.002257
Epoch  800/2000 Cost: 0.001395
Epoch  900/2000 Cost: 0.000862
Epoch 1000/2000 Cost: 0.000533
Epoch 1100/2000 Cost: 0.000329
Epoch 1200/2000 Cost: 0.000203
Epoch 1300/2000 Cost: 0.000126
Epoch 1400/2000 Cost: 0.000078
Epoch 1500/2000 Cost: 0.000048
Epoch 1600/2000 Cost: 0.000030
Epoch 1700/2000 Cost: 0.000018
Epoch 1800/2000 Cost: 0.000011
Epoch 1900/2000 Cost: 0.000007
Epoch 2000/2000 Cost: 0.000004


In [ ]:
# 다중 선형 회귀 클래스로 구현하기
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

In [75]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [74]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)

    def forward(self, x):
        return self.linear(x)

In [76]:
model = MultivariateLinearRegressionModel()

In [77]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

In [78]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    prediction = model(x_train)

    cost = F.mse_loss(prediction, y_train) 

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 31362.458984
Epoch  100/2000 Cost: 0.267419
Epoch  200/2000 Cost: 0.266823
Epoch  300/2000 Cost: 0.266239
Epoch  400/2000 Cost: 0.265651
Epoch  500/2000 Cost: 0.265086
Epoch  600/2000 Cost: 0.264524
Epoch  700/2000 Cost: 0.263962
Epoch  800/2000 Cost: 0.263412
Epoch  900/2000 Cost: 0.262871
Epoch 1000/2000 Cost: 0.262337
Epoch 1100/2000 Cost: 0.261808
Epoch 1200/2000 Cost: 0.261285
Epoch 1300/2000 Cost: 0.260773
Epoch 1400/2000 Cost: 0.260260
Epoch 1500/2000 Cost: 0.259755
Epoch 1600/2000 Cost: 0.259250
Epoch 1700/2000 Cost: 0.258762
Epoch 1800/2000 Cost: 0.258269
Epoch 1900/2000 Cost: 0.257777
Epoch 2000/2000 Cost: 0.257306


#### 미니 배치와 데이터 로드
미니 배치를 사용할 경우  
데이터를 미니 배치 수 만큼 나눠 학습을 진행하는데  
연산량이 적어 훈련 속도는 빠르지만, 최적의 값을 찾아내는 데는 오래 걸릴 수 있음  

배치 크기는 보통 2의 제곱 수를 이용하는데 이는 데이터 송수신의 효율을 높이기 때문  

In [79]:
# 데이터 로드하기
import torch
import torch.nn as nn
import torch.nn.functional as F

In [80]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

In [81]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  90], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [82]:
dataset = TensorDataset(x_train, y_train) # 텐서를 입력으로 받음

In [84]:
dataloader = DataLoader(dataset, batch_size = 2, shuffle=True) # shuffle=True : 문제 순서에 대한 학습을 줄이기 위해 사용

In [85]:
model = nn.Linear(3, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [87]:
nb_epochs = 20

for epoch in range(nb_epochs + 1):
  for batch_idx, samples in enumerate(dataloader):
    x_train, y_train = samples

    prediction = model(x_train)

    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

Epoch    0/20 Batch 1/3 Cost: 5597.213867
Epoch    0/20 Batch 2/3 Cost: 934.250916
Epoch    0/20 Batch 3/3 Cost: 280.980530
Epoch    1/20 Batch 1/3 Cost: 150.308685
Epoch    1/20 Batch 2/3 Cost: 62.545269
Epoch    1/20 Batch 3/3 Cost: 12.158208
Epoch    2/20 Batch 1/3 Cost: 4.385422
Epoch    2/20 Batch 2/3 Cost: 6.497827
Epoch    2/20 Batch 3/3 Cost: 1.120168
Epoch    3/20 Batch 1/3 Cost: 1.985241
Epoch    3/20 Batch 2/3 Cost: 1.905858
Epoch    3/20 Batch 3/3 Cost: 2.208310
Epoch    4/20 Batch 1/3 Cost: 1.356321
Epoch    4/20 Batch 2/3 Cost: 0.274163
Epoch    4/20 Batch 3/3 Cost: 4.047381
Epoch    5/20 Batch 1/3 Cost: 2.102596
Epoch    5/20 Batch 2/3 Cost: 2.085853
Epoch    5/20 Batch 3/3 Cost: 0.350025
Epoch    6/20 Batch 1/3 Cost: 1.894480
Epoch    6/20 Batch 2/3 Cost: 0.429007
Epoch    6/20 Batch 3/3 Cost: 2.874240
Epoch    7/20 Batch 1/3 Cost: 0.043304
Epoch    7/20 Batch 2/3 Cost: 1.365321
Epoch    7/20 Batch 3/3 Cost: 4.383406
Epoch    8/20 Batch 1/3 Cost: 0.818015
Epoch    8/20 

In [88]:
new_var =  torch.FloatTensor([[73, 80, 75]]) 
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[152.0009]], grad_fn=<AddmmBackward>)


#### 커스텀 데이터셋

In [ ]:
# 커스텀 데이터셋(Custom Dataset)으로 선형 회귀 구현하기
import torch
import torch.nn.functional as F

In [91]:
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [92]:
class CustomDataset(Dataset): 
  def __init__(self):
    self.x_data = [[73, 80, 75],
                   [93, 88, 93],
                   [89, 91, 90],
                   [96, 98, 100],
                   [73, 66, 70]]
    self.y_data = [[152], [185], [180], [196], [142]]

  # 총 데이터의 개수를 리턴
  def __len__(self): 
    return len(self.x_data)

  # 인덱스를 입력받아 그에 맵핑되는 입출력 데이터를 파이토치의 Tensor 형태로 리턴
  def __getitem__(self, idx): 
    x = torch.FloatTensor(self.x_data[idx])
    y = torch.FloatTensor(self.y_data[idx])
    return x, y

In [93]:
dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [94]:
model = torch.nn.Linear(3, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [95]:
nb_epochs = 20

for epoch in range(nb_epochs + 1):
    for batch_idx, samples in enumerate(dataloader):
        x_train, y_train = samples

        prediction = model(x_train)

        cost = F.mse_loss(prediction, y_train)

        optimizer.zero_grad()
        cost.backward()
        optimizer.step()

        print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

Epoch    0/20 Batch 1/3 Cost: 37462.480469
Epoch    0/20 Batch 2/3 Cost: 8415.630859
Epoch    0/20 Batch 3/3 Cost: 2263.950928
Epoch    1/20 Batch 1/3 Cost: 1108.097168
Epoch    1/20 Batch 2/3 Cost: 457.514771
Epoch    1/20 Batch 3/3 Cost: 75.030289
Epoch    2/20 Batch 1/3 Cost: 38.075111
Epoch    2/20 Batch 2/3 Cost: 13.430143
Epoch    2/20 Batch 3/3 Cost: 6.588947
Epoch    3/20 Batch 1/3 Cost: 1.811704
Epoch    3/20 Batch 2/3 Cost: 1.153313
Epoch    3/20 Batch 3/3 Cost: 1.377478
Epoch    4/20 Batch 1/3 Cost: 0.163789
Epoch    4/20 Batch 2/3 Cost: 1.789759
Epoch    4/20 Batch 3/3 Cost: 1.047862
Epoch    5/20 Batch 1/3 Cost: 1.104023
Epoch    5/20 Batch 2/3 Cost: 0.684501
Epoch    5/20 Batch 3/3 Cost: 0.742596
Epoch    6/20 Batch 1/3 Cost: 0.163156
Epoch    6/20 Batch 2/3 Cost: 0.584086
Epoch    6/20 Batch 3/3 Cost: 2.681996
Epoch    7/20 Batch 1/3 Cost: 0.533756
Epoch    7/20 Batch 2/3 Cost: 0.991640
Epoch    7/20 Batch 3/3 Cost: 1.071675
Epoch    8/20 Batch 1/3 Cost: 0.364733
Epoch  

In [96]:
new_var =  torch.FloatTensor([[73, 80, 75]]) 
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.3290]], grad_fn=<AddmmBackward>)
